// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class eMaterialFeedOpType implements java.io.Serializable
{
    public static final int _eMaterialFeedOpTypeFeedShare = 0;
    public static final int _eMaterialFeedOpTypeFeedTry = 1;
    public static final int _eMaterialFeedOpTypeFeedDetail = 2;
    public static final int _eMaterialFeedOpTypeTagDetail = 3;
}
