// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class eMaterialFeedAttrType implements java.io.Serializable
{
    public static final int _eMaterialFeedAttrTypeStar = 0;
    public static final int _eMaterialFeedAttrTypeShare = 1;
    public static final int _eMaterialFeedAttrTypeTry = 2;
    public static final int _eMaterialFeedAttrTypeView = 3;
}
