// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class eMaterialFeedTagNumType implements java.io.Serializable
{
    public static final int _eMaterialFeedTagNumTypePV = 0;
    public static final int _eMaterialFeedTagNumTypeUV = 1;
    public static final int _eMaterialFeedTagNumTypeFeeds = 2;
}
