// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaMaterialFeedItem extends com.qq.taf.jce.JceStruct
{
    public int type = 0;

    public stMetaMaterialFeedImage image = null;

    public stMetaMaterialFeedVideo video = null;

    public String desc = "";

    public String jump_url = "";

    public stMetaMaterialFeedItem()
    {
    }

    public stMetaMaterialFeedItem(int type, stMetaMaterialFeedImage image, stMetaMaterialFeedVideo video, String desc, String jump_url)
    {
        this.type = type;
        this.image = image;
        this.video = video;
        this.desc = desc;
        this.jump_url = jump_url;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
        if (null != image)
        {
            _os.write(image, 1);
        }
        if (null != video)
        {
            _os.write(video, 2);
        }
        if (null != desc)
        {
            _os.write(desc, 3);
        }
        if (null != jump_url)
        {
            _os.write(jump_url, 4);
        }
    }

    static int cache_type;
    static {
        cache_type = 0;
    }
    static stMetaMaterialFeedImage cache_image;
    static {
        cache_image = new stMetaMaterialFeedImage();
    }
    static stMetaMaterialFeedVideo cache_video;
    static {
        cache_video = new stMetaMaterialFeedVideo();
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.type = (int) _is.read(type, 0, false);
        this.image = (stMetaMaterialFeedImage) _is.read(cache_image, 1, false);
        this.video = (stMetaMaterialFeedVideo) _is.read(cache_video, 2, false);
        this.desc =  _is.readString(3, false);
        this.jump_url =  _is.readString(4, false);
    }

}

