// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaMaterialFeed extends com.qq.taf.jce.JceStruct
{
    public String feed_id = "";

    public stMetaUser poster = null;

    public int timestamp = 0;

    public String title = "";

    public String desc = "";

    public java.util.ArrayList<stMetaMaterialFeedTag> tags = null;

    public int type = 0;    // 客户端：如果 type 设为 -1，说明是 Fake feed

    public stMetaMaterialFeedItem preview = null;

    public java.util.ArrayList<stMetaMaterialFeedItem> contents = null;

    public java.util.Map<Integer, Integer> numbers = null;

    public java.util.Map<Integer, Integer> display_ui = null;

    public String h5_url = "";

    public int status = 0;

    public stMetaMaterialFeed()
    {
    }

    public stMetaMaterialFeed(String feed_id, stMetaUser poster, int timestamp, String title, String desc, java.util.ArrayList<stMetaMaterialFeedTag> tags, int type, stMetaMaterialFeedItem preview, java.util.ArrayList<stMetaMaterialFeedItem> contents, java.util.Map<Integer, Integer> numbers, java.util.Map<Integer, Integer> display_ui, String h5_url, int status)
    {
        this.feed_id = feed_id;
        this.poster = poster;
        this.timestamp = timestamp;
        this.title = title;
        this.desc = desc;
        this.tags = tags;
        this.type = type;
        this.preview = preview;
        this.contents = contents;
        this.numbers = numbers;
        this.display_ui = display_ui;
        this.h5_url = h5_url;
        this.status = status;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != feed_id)
        {
            _os.write(feed_id, 0);
        }
        if (null != poster)
        {
            _os.write(poster, 1);
        }
        _os.write(timestamp, 2);
        if (null != title)
        {
            _os.write(title, 3);
        }
        if (null != desc)
        {
            _os.write(desc, 4);
        }
        if (null != tags)
        {
            _os.write(tags, 5);
        }
        _os.write(type, 6);
        if (null != preview)
        {
            _os.write(preview, 7);
        }
        if (null != contents)
        {
            _os.write(contents, 8);
        }
        if (null != numbers)
        {
            _os.write(numbers, 9);
        }
        if (null != display_ui)
        {
            _os.write(display_ui, 10);
        }
        if (null != h5_url)
        {
            _os.write(h5_url, 11);
        }
        _os.write(status, 12);
    }

    static stMetaUser cache_poster;
    static {
        cache_poster = new stMetaUser();
    }
    static java.util.ArrayList<stMetaMaterialFeedTag> cache_tags;
    static {
        cache_tags = new java.util.ArrayList<stMetaMaterialFeedTag>();
        stMetaMaterialFeedTag __var_8 = new stMetaMaterialFeedTag();
        ((java.util.ArrayList<stMetaMaterialFeedTag>)cache_tags).add(__var_8);
    }
    static int cache_type;
    static {
        cache_type = 0;
    }
    static stMetaMaterialFeedItem cache_preview;
    static {
        cache_preview = new stMetaMaterialFeedItem();
    }
    static java.util.ArrayList<stMetaMaterialFeedItem> cache_contents;
    static {
        cache_contents = new java.util.ArrayList<stMetaMaterialFeedItem>();
        stMetaMaterialFeedItem __var_9 = new stMetaMaterialFeedItem();
        ((java.util.ArrayList<stMetaMaterialFeedItem>)cache_contents).add(__var_9);
    }
    static java.util.Map<Integer, Integer> cache_numbers;
    static {
        cache_numbers = new java.util.HashMap<Integer, Integer>();
        Integer __var_10 = 0;
        Integer __var_11 = 0;
        cache_numbers.put(__var_10, __var_11);
    }
    static java.util.Map<Integer, Integer> cache_display_ui;
    static {
        cache_display_ui = new java.util.HashMap<Integer, Integer>();
        Integer __var_12 = 0;
        Integer __var_13 = 0;
        cache_display_ui.put(__var_12, __var_13);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.feed_id =  _is.readString(0, false);
        this.poster = (stMetaUser) _is.read(cache_poster, 1, false);
        this.timestamp = (int) _is.read(timestamp, 2, false);
        this.title =  _is.readString(3, false);
        this.desc =  _is.readString(4, false);
        this.tags = (java.util.ArrayList<stMetaMaterialFeedTag>) _is.read(cache_tags, 5, false);
        this.type = (int) _is.read(type, 6, false);
        this.preview = (stMetaMaterialFeedItem) _is.read(cache_preview, 7, false);
        this.contents = (java.util.ArrayList<stMetaMaterialFeedItem>) _is.read(cache_contents, 8, false);
        this.numbers = (java.util.Map<Integer, Integer>) _is.read(cache_numbers, 9, false);
        this.display_ui = (java.util.Map<Integer, Integer>) _is.read(cache_display_ui, 10, false);
        this.h5_url =  _is.readString(11, false);
        this.status = (int) _is.read(status, 12, false);
    }

    public boolean isFeedAd() {
        return type == eMaterialFeedType._eMaterialFeedTypeGuide;
    }

    public boolean isFakeFeed() {
        return type < 0;
    }

    public boolean isPreviewVideo() {
        if (preview == null){
            return false;
        }
        return preview.type == eMaterialFeedItemType._eMaterialFeedItemTypeVideo;
    }

    public boolean isNormalOrAd() {
        return type == eMaterialFeedType._eMaterialFeedTypeGuide || type == eMaterialFeedType._eMaterialFeedTypeNormal;
    }

    public boolean isContentVideo() {
        boolean contentVideo = false;
        if (contents != null && !contents.isEmpty()) {
            if (contents.get(0).type == eMaterialFeedItemType._eMaterialFeedItemTypeVideo) {
                contentVideo = true;
            }
        }
        return contentVideo;
    }

}

