// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaMaterialFeedImage extends com.qq.taf.jce.JceStruct
{
    public String image_base = "";

    public int origin_width = 0;

    public int origin_height = 0;

    public java.util.Map<Integer, String> urls = null;

    public stMetaMaterialFeedImage()
    {
    }

    public stMetaMaterialFeedImage(String image_base, int origin_width, int origin_height, java.util.Map<Integer, String> urls)
    {
        this.image_base = image_base;
        this.origin_width = origin_width;
        this.origin_height = origin_height;
        this.urls = urls;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != image_base)
        {
            _os.write(image_base, 0);
        }
        _os.write(origin_width, 1);
        _os.write(origin_height, 2);
        if (null != urls)
        {
            _os.write(urls, 3);
        }
    }

    static java.util.Map<Integer, String> cache_urls;
    static {
        cache_urls = new java.util.HashMap<Integer, String>();
        Integer __var_2 = 0;
        String __var_3 = "";
        cache_urls.put(__var_2, __var_3);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.image_base =  _is.readString(0, false);
        this.origin_width = (int) _is.read(origin_width, 1, false);
        this.origin_height = (int) _is.read(origin_height, 2, false);
        this.urls = (java.util.Map<Integer, String>) _is.read(cache_urls, 3, false);
    }

}

