// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaVector extends com.qq.taf.jce.JceStruct
{
    public java.util.ArrayList<String> str_data = null;

    public java.util.ArrayList<Long> num_data = null;

    public stMetaVector()
    {
    }

    public stMetaVector(java.util.ArrayList<String> str_data, java.util.ArrayList<Long> num_data)
    {
        this.str_data = str_data;
        this.num_data = num_data;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != str_data)
        {
            _os.write(str_data, 0);
        }
        if (null != num_data)
        {
            _os.write(num_data, 1);
        }
    }

    static java.util.ArrayList<String> cache_str_data;
    static {
        cache_str_data = new java.util.ArrayList<String>();
        String __var_14 = "";
        ((java.util.ArrayList<String>)cache_str_data).add(__var_14);
    }
    static java.util.ArrayList<Long> cache_num_data;
    static {
        cache_num_data = new java.util.ArrayList<Long>();
        Long __var_15 = 0L;
        ((java.util.ArrayList<Long>)cache_num_data).add(__var_15);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.str_data = (java.util.ArrayList<String>) _is.read(cache_str_data, 0, false);
        this.num_data = (java.util.ArrayList<Long>) _is.read(cache_num_data, 1, false);
    }

}

