// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaMaterialFeedVideo extends com.qq.taf.jce.JceStruct
{
    public stMetaMaterialFeedImage cover_image = null;

    public int origin_width = 0;

    public int origin_height = 0;

    public String video_base_info = "";

    public java.util.Map<Integer, String> urls = null;

    public stMetaMaterialFeedVideo()
    {
    }

    public stMetaMaterialFeedVideo(stMetaMaterialFeedImage cover_image, int origin_width, int origin_height, String video_base_info, java.util.Map<Integer, String> urls)
    {
        this.cover_image = cover_image;
        this.origin_width = origin_width;
        this.origin_height = origin_height;
        this.video_base_info = video_base_info;
        this.urls = urls;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != cover_image)
        {
            _os.write(cover_image, 0);
        }
        _os.write(origin_width, 1);
        _os.write(origin_height, 2);
        if (null != video_base_info)
        {
            _os.write(video_base_info, 3);
        }
        if (null != urls)
        {
            _os.write(urls, 4);
        }
    }

    static stMetaMaterialFeedImage cache_cover_image;
    static {
        cache_cover_image = new stMetaMaterialFeedImage();
    }
    static java.util.Map<Integer, String> cache_urls;
    static {
        cache_urls = new java.util.HashMap<Integer, String>();
        Integer __var_4 = 0;
        String __var_5 = "";
        cache_urls.put(__var_4, __var_5);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.cover_image = (stMetaMaterialFeedImage) _is.read(cache_cover_image, 0, false);
        this.origin_width = (int) _is.read(origin_width, 1, false);
        this.origin_height = (int) _is.read(origin_height, 2, false);
        this.video_base_info =  _is.readString(3, false);
        this.urls = (java.util.Map<Integer, String>) _is.read(cache_urls, 4, false);
    }

}

