// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaUser extends com.qq.taf.jce.JceStruct
{
    public String uid = "";

    public String openid = "";

    public int type = 0;

    public int createtime = 0;

    public String nick = "";

    public String avatar = "";

    public int sex = 0;

    public int age = 0;

    public String address = "";

    public int rich_flag = 0;

    public stMetaUser()
    {
    }

    public stMetaUser(String uid, String openid, int type, int createtime, String nick, String avatar, int sex, int age, String address, int rich_flag)
    {
        this.uid = uid;
        this.openid = openid;
        this.type = type;
        this.createtime = createtime;
        this.nick = nick;
        this.avatar = avatar;
        this.sex = sex;
        this.age = age;
        this.address = address;
        this.rich_flag = rich_flag;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != uid)
        {
            _os.write(uid, 1);
        }
        if (null != openid)
        {
            _os.write(openid, 2);
        }
        _os.write(type, 3);
        _os.write(createtime, 4);
        if (null != nick)
        {
            _os.write(nick, 5);
        }
        if (null != avatar)
        {
            _os.write(avatar, 6);
        }
        _os.write(sex, 7);
        _os.write(age, 8);
        if (null != address)
        {
            _os.write(address, 9);
        }
        _os.write(rich_flag, 10);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.uid =  _is.readString(1, false);
        this.openid =  _is.readString(2, false);
        this.type = (int) _is.read(type, 3, false);
        this.createtime = (int) _is.read(createtime, 4, false);
        this.nick =  _is.readString(5, false);
        this.avatar =  _is.readString(6, false);
        this.sex = (int) _is.read(sex, 7, false);
        this.age = (int) _is.read(age, 8, false);
        this.address =  _is.readString(9, false);
        this.rich_flag = (int) _is.read(rich_flag, 10, false);
    }

}

