// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stMetaMaterialFeedTag extends com.qq.taf.jce.JceStruct
{
    // 0000,0001 - 是否推荐 tag（高亮）
    public static final int MASK_IS_RECOMMENDED = 0x1;  // 是否官方推荐 tag

    public String name = "";

    public String desc = "";

    public long mask = 0;

    public java.util.Map<Integer, Integer> numbers = null;

    public stMetaMaterialFeedTag()
    {
    }

    public stMetaMaterialFeedTag(String name, String desc, long mask, java.util.Map<Integer, Integer> numbers)
    {
        this.name = name;
        this.desc = desc;
        this.mask = mask;
        this.numbers = numbers;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != name)
        {
            _os.write(name, 0);
        }
        if (null != desc)
        {
            _os.write(desc, 1);
        }
        _os.write(mask, 2);
        if (null != numbers)
        {
            _os.write(numbers, 3);
        }
    }

    static java.util.Map<Integer, Integer> cache_numbers;
    static {
        cache_numbers = new java.util.HashMap<Integer, Integer>();
        Integer __var_6 = 0;
        Integer __var_7 = 0;
        cache_numbers.put(__var_6, __var_7);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.name =  _is.readString(0, false);
        this.desc =  _is.readString(1, false);
        this.mask = (long) _is.read(mask, 2, false);
        this.numbers = (java.util.Map<Integer, Integer>) _is.read(cache_numbers, 3, false);
    }

    public boolean isRecommended() {
        return (mask & MASK_IS_RECOMMENDED) == MASK_IS_RECOMMENDED;
    }

}

