// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/pitu_meta_protocol.jce'
// **********************************************************************

package NS_PITU_META_PROTOCOL;

public final class stUserWealthInfo extends com.qq.taf.jce.JceStruct
{
    public int pitub = 0;

    public stUserWealthInfo()
    {
    }

    public stUserWealthInfo(int pitub)
    {
        this.pitub = pitub;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(pitub, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.pitub = (int) _is.read(pitub, 0, false);
    }

}

