// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stBanner extends com.qq.taf.jce.JceStruct
{
    public long id = 0;

    public String picUrl = "";

    public long timeFinish = 0;

    public int mode = 0;

    public String url = "";

    public String language = "";

    public stBanner()
    {
    }

    public stBanner(long id, String picUrl, long timeFinish, int mode, String url, String language)
    {
        this.id = id;
        this.picUrl = picUrl;
        this.timeFinish = timeFinish;
        this.mode = mode;
        this.url = url;
        this.language = language;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(picUrl, 1);
        _os.write(timeFinish, 2);
        _os.write(mode, 3);
        _os.write(url, 4);
        if (null != language)
        {
            _os.write(language, 5);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id = (long) _is.read(id, 0, true);
        this.picUrl =  _is.readString(1, true);
        this.timeFinish = (long) _is.read(timeFinish, 2, true);
        this.mode = (int) _is.read(mode, 3, true);
        this.url =  _is.readString(4, true);
        this.language =  _is.readString(5, false);
    }

}

