// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/geraldzhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stBuyMaterialRsp extends com.qq.taf.jce.JceStruct
{
    public String buyUrl = "";

    public stBuyMaterialRsp()
    {
    }

    public stBuyMaterialRsp(String buyUrl)
    {
        this.buyUrl = buyUrl;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != buyUrl)
        {
            _os.write(buyUrl, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.buyUrl =  _is.readString(0, false);
    }

}

