// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/geraldzhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stBuyMaterialReq extends com.qq.taf.jce.JceStruct
{
    public String materialId = "";

    public String materialName = "";

    public String materialDesc = "";

    public stBuyMaterialReq()
    {
    }

    public stBuyMaterialReq(String materialId, String materialName, String materialDesc)
    {
        this.materialId = materialId;
        this.materialName = materialName;
        this.materialDesc = materialDesc;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != materialId)
        {
            _os.write(materialId, 0);
        }
        if (null != materialName)
        {
            _os.write(materialName, 1);
        }
        if (null != materialDesc)
        {
            _os.write(materialDesc, 2);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.materialId =  _is.readString(0, false);
        this.materialName =  _is.readString(1, false);
        this.materialDesc =  _is.readString(2, false);
    }

}

