// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stCategoryItem extends com.qq.taf.jce.JceStruct
{
    public String id = "";

    public String name = "";

    public int priority = 1;

    public java.util.ArrayList<stCategoryItem> subCategories = null;

    public String language = "";

    public String iconUrl = "";

    public int version = 0;

    public stCategoryItem()
    {
    }

    public stCategoryItem(String id, String name, int priority, java.util.ArrayList<stCategoryItem> subCategories, String language, String iconUrl, int version)
    {
        this.id = id;
        this.name = name;
        this.priority = priority;
        this.subCategories = subCategories;
        this.language = language;
        this.iconUrl = iconUrl;
        this.version = version;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(name, 1);
        _os.write(priority, 2);
        _os.write(subCategories, 3);
        _os.write(language, 4);
        _os.write(iconUrl, 5);
        _os.write(version, 6);
    }

    static java.util.ArrayList<stCategoryItem> cache_subCategories;
    static {
        cache_subCategories = new java.util.ArrayList<stCategoryItem>();
        stCategoryItem __var_9 = new stCategoryItem();
        ((java.util.ArrayList<stCategoryItem>)cache_subCategories).add(__var_9);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id =  _is.readString(0, true);
        this.name =  _is.readString(1, true);
        this.priority = (int) _is.read(priority, 2, true);
        this.subCategories = (java.util.ArrayList<stCategoryItem>) _is.read(cache_subCategories, 3, true);
        this.language =  _is.readString(4, true);
        this.iconUrl =  _is.readString(5, true);
        this.version = (int) _is.read(version, 6, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stCategoryItem temp = JSON.parseObject(text, stCategoryItem.class);
        this.id = temp.id;
        this.name = temp.name;
        this.priority = temp.priority;
        this.subCategories = temp.subCategories;
        this.language = temp.language;
        this.iconUrl = temp.iconUrl;
        this.version = temp.version;
    }

}

