// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface_3.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stConvertShortUrlReq extends com.qq.taf.jce.JceStruct
{
    public String longUrl = "";

    public stConvertShortUrlReq()
    {
    }

    public stConvertShortUrlReq(String longUrl)
    {
        this.longUrl = longUrl;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(longUrl, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.longUrl =  _is.readString(0, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stConvertShortUrlReq temp = JSON.parseObject(text, stConvertShortUrlReq.class);
        this.longUrl = temp.longUrl;
    }

}

