// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stDoPrismaFilterReq extends com.qq.taf.jce.JceStruct
{
    public String filterId = "";

    public byte [] photoData = null;

    public int width = 0;

    public int height = 0;

    public stDoPrismaFilterReq()
    {
    }

    public stDoPrismaFilterReq(String filterId, byte [] photoData, int width, int height)
    {
        this.filterId = filterId;
        this.photoData = photoData;
        this.width = width;
        this.height = height;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(filterId, 0);
        _os.write(photoData, 1);
        _os.write(width, 2);
        _os.write(height, 3);
    }

    static byte [] cache_photoData;
    static {
        cache_photoData = (byte[]) new byte[1];
        byte __var_23 = 0;
        ((byte[])cache_photoData)[0] = __var_23;
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.filterId =  _is.readString(0, true);
        this.photoData = (byte []) _is.read(cache_photoData, 1, true);
        this.width = (int) _is.read(width, 2, true);
        this.height = (int) _is.read(height, 3, true);
    }

}

