// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stDoPrismaFilterRsp extends com.qq.taf.jce.JceStruct
{
    public byte [] photoData = null;

    public stDoPrismaFilterRsp()
    {
    }

    public stDoPrismaFilterRsp(byte [] photoData)
    {
        this.photoData = photoData;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(photoData, 0);
    }

    static byte [] cache_photoData;
    static {
        cache_photoData = (byte[]) new byte[1];
        byte __var_24 = 0;
        ((byte[])cache_photoData)[0] = __var_24;
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.photoData = (byte []) _is.read(cache_photoData, 0, true);
    }

}

