// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetOpInfoRsp extends com.qq.taf.jce.JceStruct
{
    public java.util.ArrayList<stOpData> opDatas = null;

    public int attachInfo = 0;

    public stGetOpInfoRsp()
    {
    }

    public stGetOpInfoRsp(java.util.ArrayList<stOpData> opDatas, int attachInfo)
    {
        this.opDatas = opDatas;
        this.attachInfo = attachInfo;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != opDatas)
        {
            _os.write(opDatas, 0);
        }
        _os.write(attachInfo, 1);
    }

    static java.util.ArrayList<stOpData> cache_opDatas;
    static {
        cache_opDatas = new java.util.ArrayList<stOpData>();
        stOpData __var_16 = new stOpData();
        ((java.util.ArrayList<stOpData>)cache_opDatas).add(__var_16);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.opDatas = (java.util.ArrayList<stOpData>) _is.read(cache_opDatas, 0, false);
        this.attachInfo = (int) _is.read(attachInfo, 1, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetOpInfoRsp temp = JSON.parseObject(text, stGetOpInfoRsp.class);
        this.opDatas = temp.opDatas;
        this.attachInfo = temp.attachInfo;
    }

}

