// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetMusicMaterialsReq extends com.qq.taf.jce.JceStruct
{
    public String attachInfo = "";

    public String categoryId = "";

    public stGetMusicMaterialsReq()
    {
    }

    public stGetMusicMaterialsReq(String attachInfo, String categoryId)
    {
        this.attachInfo = attachInfo;
        this.categoryId = categoryId;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(attachInfo, 0);
        _os.write(categoryId, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attachInfo =  _is.readString(0, true);
        this.categoryId =  _is.readString(1, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetMusicMaterialsReq temp = JSON.parseObject(text, stGetMusicMaterialsReq.class);
        this.attachInfo = temp.attachInfo;
        this.categoryId = temp.categoryId;
    }

}

