// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetMusicCategoryTreeRsp extends com.qq.taf.jce.JceStruct
{
    public stCategoryItem musicCategoryRoot = null;

    public stGetMusicCategoryTreeRsp()
    {
    }

    public stGetMusicCategoryTreeRsp(stCategoryItem musicCategoryRoot)
    {
        this.musicCategoryRoot = musicCategoryRoot;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != musicCategoryRoot)
        {
            _os.write(musicCategoryRoot, 0);
        }
    }

    static stCategoryItem cache_musicCategoryRoot;
    static {
        cache_musicCategoryRoot = new stCategoryItem();
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.musicCategoryRoot = (stCategoryItem) _is.read(cache_musicCategoryRoot, 0, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetMusicCategoryTreeRsp temp = JSON.parseObject(text, stGetMusicCategoryTreeRsp.class);
        this.musicCategoryRoot = temp.musicCategoryRoot;
    }

}

