// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kenneyqin/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetAndroidUpgradeNoticeRsp extends com.qq.taf.jce.JceStruct
{
    public String attachInfo = "";

    public int result = 0;

    public String title = "";

    public String whatisnew = "";

    public String updatebuttontext = "";

    public String cancelbuttontext = "";

    public String apkurl = "";

    public stGetAndroidUpgradeNoticeRsp()
    {
    }

    public stGetAndroidUpgradeNoticeRsp(String attachInfo, int result, String title, String whatisnew, String updatebuttontext, String cancelbuttontext, String apkurl)
    {
        this.attachInfo = attachInfo;
        this.result = result;
        this.title = title;
        this.whatisnew = whatisnew;
        this.updatebuttontext = updatebuttontext;
        this.cancelbuttontext = cancelbuttontext;
        this.apkurl = apkurl;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != attachInfo)
        {
            _os.write(attachInfo, 0);
        }
        _os.write(result, 1);
        if (null != title)
        {
            _os.write(title, 2);
        }
        if (null != whatisnew)
        {
            _os.write(whatisnew, 3);
        }
        if (null != updatebuttontext)
        {
            _os.write(updatebuttontext, 4);
        }
        if (null != cancelbuttontext)
        {
            _os.write(cancelbuttontext, 5);
        }
        if (null != apkurl)
        {
            _os.write(apkurl, 6);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attachInfo =  _is.readString(0, false);
        this.result = (int) _is.read(result, 1, false);
        this.title =  _is.readString(2, false);
        this.whatisnew =  _is.readString(3, false);
        this.updatebuttontext =  _is.readString(4, false);
        this.cancelbuttontext =  _is.readString(5, false);
        this.apkurl =  _is.readString(6, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetAndroidUpgradeNoticeRsp temp = JSON.parseObject(text, stGetAndroidUpgradeNoticeRsp.class);
        this.attachInfo = temp.attachInfo;
        this.result = temp.result;
        this.title = temp.title;
        this.whatisnew = temp.whatisnew;
        this.updatebuttontext = temp.updatebuttontext;
        this.cancelbuttontext = temp.cancelbuttontext;
        this.apkurl = temp.apkurl;
    }

}

