// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetWatermarkDictRsp extends com.qq.taf.jce.JceStruct
{
    public java.util.Map<String, String> watermarkDict = null;

    public stGetWatermarkDictRsp()
    {
    }

    public stGetWatermarkDictRsp(java.util.Map<String, String> watermarkDict)
    {
        this.watermarkDict = watermarkDict;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(watermarkDict, 0);
    }

    static java.util.Map<String, String> cache_watermarkDict;
    static {
        cache_watermarkDict = new java.util.HashMap<String, String>();
        String __var_23 = "";
        String __var_24 = "";
        cache_watermarkDict.put(__var_23, __var_24);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.watermarkDict = (java.util.Map<String, String>) _is.read(cache_watermarkDict, 0, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetWatermarkDictRsp temp = JSON.parseObject(text, stGetWatermarkDictRsp.class);
        this.watermarkDict = temp.watermarkDict;
    }

}

