// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetWatermarkDictReq extends com.qq.taf.jce.JceStruct
{
    public double fLat = 900;

    public double fLon = 900;

    public String clientIP = "";

    public stGetWatermarkDictReq()
    {
    }

    public stGetWatermarkDictReq(double fLat, double fLon, String clientIP)
    {
        this.fLat = fLat;
        this.fLon = fLon;
        this.clientIP = clientIP;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(fLat, 0);
        _os.write(fLon, 1);
        _os.write(clientIP, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.fLat = (double) _is.read(fLat, 0, true);
        this.fLon = (double) _is.read(fLon, 1, true);
        this.clientIP =  _is.readString(2, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetWatermarkDictReq temp = JSON.parseObject(text, stGetWatermarkDictReq.class);
        this.fLat = temp.fLat;
        this.fLon = temp.fLon;
        this.clientIP = temp.clientIP;
    }

}

