// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetOpInfoReq extends com.qq.taf.jce.JceStruct
{
    public int attachInfo = 0;

    public stGetOpInfoReq()
    {
    }

    public stGetOpInfoReq(int attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(attachInfo, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attachInfo = (int) _is.read(attachInfo, 0, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetOpInfoReq temp = JSON.parseObject(text, stGetOpInfoReq.class);
        this.attachInfo = temp.attachInfo;
    }

}

