// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kenneyqin/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetAndroidUpgradeNoticeReq extends com.qq.taf.jce.JceStruct
{
    public String attachInfo = "";

    public stGetAndroidUpgradeNoticeReq()
    {
    }

    public stGetAndroidUpgradeNoticeReq(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != attachInfo)
        {
            _os.write(attachInfo, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attachInfo =  _is.readString(0, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetAndroidUpgradeNoticeReq temp = JSON.parseObject(text, stGetAndroidUpgradeNoticeReq.class);
        this.attachInfo = temp.attachInfo;
    }

}

