// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetSimpleConfigReq extends com.qq.taf.jce.JceStruct
{
    public java.util.Map<String, String> oldConfig = null;

    public stGetSimpleConfigReq()
    {
    }

    public stGetSimpleConfigReq(java.util.Map<String, String> oldConfig)
    {
        this.oldConfig = oldConfig;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(oldConfig, 0);
    }

    static java.util.Map<String, String> cache_oldConfig;
    static {
        cache_oldConfig = new java.util.HashMap<String, String>();
        String __var_17 = "";
        String __var_18 = "";
        cache_oldConfig.put(__var_17, __var_18);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.oldConfig = (java.util.Map<String, String>) _is.read(cache_oldConfig, 0, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetSimpleConfigReq temp = JSON.parseObject(text, stGetSimpleConfigReq.class);
        this.oldConfig = temp.oldConfig;
    }

}

