// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stGetMusicCategoryTreeReq extends com.qq.taf.jce.JceStruct
{
    public int nothing = 0;

    public int musicCategoryType = 0;

    public stGetMusicCategoryTreeReq()
    {
    }

    public stGetMusicCategoryTreeReq(int nothing, int musicCategoryType)
    {
        this.nothing = nothing;
        this.musicCategoryType = musicCategoryType;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(nothing, 0);
        _os.write(musicCategoryType, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.nothing = (int) _is.read(nothing, 0, false);
        this.musicCategoryType = (int) _is.read(musicCategoryType, 1, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stGetMusicCategoryTreeReq temp = JSON.parseObject(text, stGetMusicCategoryTreeReq.class);
        this.nothing = temp.nothing;
        this.musicCategoryType = temp.musicCategoryType;
    }

}

