// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stMaterialSubItem extends com.qq.taf.jce.JceStruct
{
    public String id = "";

    public String thumbUrl = "";

    public String name = "";

    public String desc = "";

    public stMaterialSubItem()
    {
    }

    public stMaterialSubItem(String id, String thumbUrl, String name, String desc)
    {
        this.id = id;
        this.thumbUrl = thumbUrl;
        this.name = name;
        this.desc = desc;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(thumbUrl, 1);
        if (null != name)
        {
            _os.write(name, 2);
        }
        if (null != desc)
        {
            _os.write(desc, 3);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id =  _is.readString(0, true);
        this.thumbUrl =  _is.readString(1, true);
        this.name =  _is.readString(2, false);
        this.desc =  _is.readString(3, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stMaterialSubItem temp = JSON.parseObject(text, stMaterialSubItem.class);
        this.id = temp.id;
        this.thumbUrl = temp.thumbUrl;
        this.name = temp.name;
        this.desc = temp.desc;
    }

}

