// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stMusicMaterial extends com.qq.taf.jce.JceStruct
{
    public String id = "";

    public String name = "";

    public String singer = "";

    public String tags = "";

    public String packageUrl = "";

    public String songUrl = "";

    public int timestamp = 0;

    public int songId = 0;

    public int richFlag = 0;

    public int mask = 0;

    public String thumbUrl = "";

    public stMusicMaterial()
    {
    }

    public stMusicMaterial(String id, String name, String singer, String tags, String packageUrl, String songUrl, int timestamp, int songId, int richFlag, int mask, String thumbUrl)
    {
        this.id = id;
        this.name = name;
        this.singer = singer;
        this.tags = tags;
        this.packageUrl = packageUrl;
        this.songUrl = songUrl;
        this.timestamp = timestamp;
        this.songId = songId;
        this.richFlag = richFlag;
        this.mask = mask;
        this.thumbUrl = thumbUrl;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(name, 1);
        _os.write(singer, 2);
        _os.write(tags, 3);
        _os.write(packageUrl, 4);
        _os.write(songUrl, 5);
        _os.write(timestamp, 6);
        _os.write(songId, 7);
        _os.write(richFlag, 8);
        _os.write(mask, 9);
        _os.write(thumbUrl, 10);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.id =  _is.readString(0, true);
        this.name =  _is.readString(1, true);
        this.singer =  _is.readString(2, true);
        this.tags =  _is.readString(3, true);
        this.packageUrl =  _is.readString(4, true);
        this.songUrl =  _is.readString(5, true);
        this.timestamp = (int) _is.read(timestamp, 6, true);
        this.songId = (int) _is.read(songId, 7, true);
        this.richFlag = (int) _is.read(richFlag, 8, true);
        this.mask = (int) _is.read(mask, 9, true);
        this.thumbUrl =  _is.readString(10, true);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stMusicMaterial temp = JSON.parseObject(text, stMusicMaterial.class);
        this.id = temp.id;
        this.name = temp.name;
        this.singer = temp.singer;
        this.tags = temp.tags;
        this.packageUrl = temp.packageUrl;
        this.songUrl = temp.songUrl;
        this.timestamp = temp.timestamp;
        this.songId = temp.songId;
        this.richFlag = temp.richFlag;
        this.mask = temp.mask;
        this.thumbUrl = temp.thumbUrl;
    }

}

