// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/kesenhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

import com.qq.component.json.JSON;
import com.qq.component.json.JSONException;

public final class stOpData extends com.qq.taf.jce.JceStruct
{
    public int opId = 0;

    public long timeBegin = 0;

    public long timeEnd = 0;

    public int version = 0;

    public int status = 0;

    public java.util.Map<String, String> data = null;

    public java.util.ArrayList<java.util.Map<String, String>> datas = null;

    public String language = "";

    public stOpData()
    {
    }

    public stOpData(int opId, long timeBegin, long timeEnd, int version, int status, java.util.Map<String, String> data, java.util.ArrayList<java.util.Map<String, String>> datas, String language)
    {
        this.opId = opId;
        this.timeBegin = timeBegin;
        this.timeEnd = timeEnd;
        this.version = version;
        this.status = status;
        this.data = data;
        this.datas = datas;
        this.language = language;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(opId, 0);
        _os.write(timeBegin, 1);
        _os.write(timeEnd, 2);
        _os.write(version, 3);
        _os.write(status, 4);
        _os.write(data, 5);
        if (null != datas)
        {
            _os.write(datas, 6);
        }
        if (null != language)
        {
            _os.write(language, 7);
        }
    }

    static java.util.Map<String, String> cache_data;
    static {
        cache_data = new java.util.HashMap<String, String>();
        String __var_4 = "";
        String __var_5 = "";
        cache_data.put(__var_4, __var_5);
    }
    static java.util.ArrayList<java.util.Map<String, String>> cache_datas;
    static {
        cache_datas = new java.util.ArrayList<java.util.Map<String, String>>();
        java.util.Map<String, String> __var_6 = new java.util.HashMap<String, String>();
        String __var_7 = "";
        String __var_8 = "";
        __var_6.put(__var_7, __var_8);
        ((java.util.ArrayList<java.util.Map<String, String>>)cache_datas).add(__var_6);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.opId = (int) _is.read(opId, 0, true);
        this.timeBegin = (long) _is.read(timeBegin, 1, true);
        this.timeEnd = (long) _is.read(timeEnd, 2, true);
        this.version = (int) _is.read(version, 3, true);
        this.status = (int) _is.read(status, 4, true);
        this.data = (java.util.Map<String, String>) _is.read(cache_data, 5, true);
        this.datas = (java.util.ArrayList<java.util.Map<String, String>>) _is.read(cache_datas, 6, false);
        this.language =  _is.readString(7, false);
    }

    public String writeToJsonString() throws JSONException
    {
        return JSON.toJSONString(this);
    }

    public void readFromJsonString(String text) throws JSONException
    {
        stOpData temp = JSON.parseObject(text, stOpData.class);
        this.opId = temp.opId;
        this.timeBegin = temp.timeBegin;
        this.timeEnd = temp.timeEnd;
        this.version = temp.version;
        this.status = temp.status;
        this.data = temp.data;
        this.datas = temp.datas;
        this.language = temp.language;
    }

}

