// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stPTCenterCombinReq extends com.qq.taf.jce.JceStruct
{
    public PituClientInterface.stVersions versions = null;

    public stPTCenterCombinReq()
    {
    }

    public stPTCenterCombinReq(PituClientInterface.stVersions versions)
    {
        this.versions = versions;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(versions, 0);
    }

    static PituClientInterface.stVersions cache_versions;
    static {
        cache_versions = new PituClientInterface.stVersions();
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.versions = (PituClientInterface.stVersions) _is.read(cache_versions, 0, true);
    }

}

