// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stPTCenterCombinRsp extends com.qq.taf.jce.JceStruct
{
    public PituClientInterface.stVersions curVersions = null;

    public PituClientInterface.stReturnCodes retCodes = null;

    public java.util.Map<String, PituClientInterface.stCategory> materialData = null;

    public java.util.ArrayList<PituClientInterface.stBanner> bannerData = null;

    public java.util.ArrayList<PituClientInterface.stOpData> opData = null;

    public java.util.ArrayList<PituClientInterface.stCategoryItem> categoriesInfo = null;

    public stPTCenterCombinRsp()
    {
    }

    public stPTCenterCombinRsp(PituClientInterface.stVersions curVersions, PituClientInterface.stReturnCodes retCodes, java.util.Map<String, PituClientInterface.stCategory> materialData, java.util.ArrayList<PituClientInterface.stBanner> bannerData, java.util.ArrayList<PituClientInterface.stOpData> opData, java.util.ArrayList<PituClientInterface.stCategoryItem> categoriesInfo)
    {
        this.curVersions = curVersions;
        this.retCodes = retCodes;
        this.materialData = materialData;
        this.bannerData = bannerData;
        this.opData = opData;
        this.categoriesInfo = categoriesInfo;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(curVersions, 0);
        _os.write(retCodes, 1);
        _os.write(materialData, 2);
        _os.write(bannerData, 3);
        _os.write(opData, 4);
        if (null != categoriesInfo)
        {
            _os.write(categoriesInfo, 5);
        }
    }

    static PituClientInterface.stVersions cache_curVersions;
    static {
        cache_curVersions = new PituClientInterface.stVersions();
    }
    static PituClientInterface.stReturnCodes cache_retCodes;
    static {
        cache_retCodes = new PituClientInterface.stReturnCodes();
    }
    static java.util.Map<String, PituClientInterface.stCategory> cache_materialData;
    static {
        cache_materialData = new java.util.HashMap<String, PituClientInterface.stCategory>();
        String __var_13 = "";
        PituClientInterface.stCategory __var_14 = new PituClientInterface.stCategory();
        cache_materialData.put(__var_13, __var_14);
    }
    static java.util.ArrayList<PituClientInterface.stBanner> cache_bannerData;
    static {
        cache_bannerData = new java.util.ArrayList<PituClientInterface.stBanner>();
        PituClientInterface.stBanner __var_15 = new PituClientInterface.stBanner();
        ((java.util.ArrayList<PituClientInterface.stBanner>)cache_bannerData).add(__var_15);
    }
    static java.util.ArrayList<PituClientInterface.stOpData> cache_opData;
    static {
        cache_opData = new java.util.ArrayList<PituClientInterface.stOpData>();
        PituClientInterface.stOpData __var_16 = new PituClientInterface.stOpData();
        ((java.util.ArrayList<PituClientInterface.stOpData>)cache_opData).add(__var_16);
    }
    static java.util.ArrayList<PituClientInterface.stCategoryItem> cache_categoriesInfo;
    static {
        cache_categoriesInfo = new java.util.ArrayList<PituClientInterface.stCategoryItem>();
        PituClientInterface.stCategoryItem __var_17 = new PituClientInterface.stCategoryItem();
        ((java.util.ArrayList<PituClientInterface.stCategoryItem>)cache_categoriesInfo).add(__var_17);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.curVersions = (PituClientInterface.stVersions) _is.read(cache_curVersions, 0, true);
        this.retCodes = (PituClientInterface.stReturnCodes) _is.read(cache_retCodes, 1, true);
        this.materialData = (java.util.Map<String, PituClientInterface.stCategory>) _is.read(cache_materialData, 2, true);
        this.bannerData = (java.util.ArrayList<PituClientInterface.stBanner>) _is.read(cache_bannerData, 3, true);
        this.opData = (java.util.ArrayList<PituClientInterface.stOpData>) _is.read(cache_opData, 4, true);
        this.categoriesInfo = (java.util.ArrayList<PituClientInterface.stCategoryItem>) _is.read(cache_categoriesInfo, 5, false);
    }

}

