// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stReturnCodes extends com.qq.taf.jce.JceStruct
{
    public java.util.Map<String, Integer> mainCategoryRetCodes = null;

    public int bannerRetCode = 0;

    public int opRetCode = 0;

    public int catRetCode = 0;

    public stReturnCodes()
    {
    }

    public stReturnCodes(java.util.Map<String, Integer> mainCategoryRetCodes, int bannerRetCode, int opRetCode, int catRetCode)
    {
        this.mainCategoryRetCodes = mainCategoryRetCodes;
        this.bannerRetCode = bannerRetCode;
        this.opRetCode = opRetCode;
        this.catRetCode = catRetCode;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(mainCategoryRetCodes, 0);
        _os.write(bannerRetCode, 1);
        _os.write(opRetCode, 2);
        _os.write(catRetCode, 3);
    }

    static java.util.Map<String, Integer> cache_mainCategoryRetCodes;
    static {
        cache_mainCategoryRetCodes = new java.util.HashMap<String, Integer>();
        String __var_5 = "";
        Integer __var_6 = 0;
        cache_mainCategoryRetCodes.put(__var_5, __var_6);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.mainCategoryRetCodes = (java.util.Map<String, Integer>) _is.read(cache_mainCategoryRetCodes, 0, true);
        this.bannerRetCode = (int) _is.read(bannerRetCode, 1, true);
        this.opRetCode = (int) _is.read(opRetCode, 2, true);
        this.catRetCode = (int) _is.read(catRetCode, 3, false);
    }

}

