// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/geraldzhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stSensitivePersonDetectReq extends com.qq.taf.jce.JceStruct
{
    public String raw_base64 = "";

    public stSensitivePersonDetectReq()
    {
    }

    public stSensitivePersonDetectReq(String raw_base64)
    {
        this.raw_base64 = raw_base64;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(raw_base64, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.raw_base64 =  _is.readString(0, true);
    }

}

