// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/geraldzhu/AppPituWnsInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stSensitivePersonDetectRsp extends com.qq.taf.jce.JceStruct
{
    public int score = 0;

    public stSensitivePersonDetectRsp()
    {
    }

    public stSensitivePersonDetectRsp(int score)
    {
        this.score = score;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(score, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.score = (int) _is.read(score, 0, true);
    }

}

