// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/AppPITUInterface.jce'
// **********************************************************************

package PituClientInterface;

public final class stVersions extends com.qq.taf.jce.JceStruct
{
    public java.util.Map<String, Integer> mainCategoryVersions = null;

    public int bannerVersion = 0;

    public int opVersion = 0;

    public int catInfoVersion = 0;

    public stVersions()
    {
    }

    public stVersions(java.util.Map<String, Integer> mainCategoryVersions, int bannerVersion, int opVersion, int catInfoVersion)
    {
        this.mainCategoryVersions = mainCategoryVersions;
        this.bannerVersion = bannerVersion;
        this.opVersion = opVersion;
        this.catInfoVersion = catInfoVersion;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(mainCategoryVersions, 0);
        _os.write(bannerVersion, 1);
        _os.write(opVersion, 2);
        _os.write(catInfoVersion, 3);
    }

    static java.util.Map<String, Integer> cache_mainCategoryVersions;
    static {
        cache_mainCategoryVersions = new java.util.HashMap<String, Integer>();
        String __var_3 = "";
        Integer __var_4 = 0;
        cache_mainCategoryVersions.put(__var_3, __var_4);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.mainCategoryVersions = (java.util.Map<String, Integer>) _is.read(cache_mainCategoryVersions, 0, true);
        this.bannerVersion = (int) _is.read(bannerVersion, 1, true);
        this.opVersion = (int) _is.read(opVersion, 2, true);
        this.catInfoVersion = (int) _is.read(catInfoVersion, 3, false);
    }

}

