// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetUserRsp extends com.qq.taf.jce.JceStruct
{
    public NS_PITU_META_PROTOCOL.stMetaUser user = null;

    public stGetUserRsp()
    {
    }

    public stGetUserRsp(NS_PITU_META_PROTOCOL.stMetaUser user)
    {
        this.user = user;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != user)
        {
            _os.write(user, 0);
        }
    }

    static NS_PITU_META_PROTOCOL.stMetaUser cache_user;
    static {
        cache_user = new NS_PITU_META_PROTOCOL.stMetaUser();
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.user = (NS_PITU_META_PROTOCOL.stMetaUser) _is.read(cache_user, 0, false);
    }

}

