// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetTagDetailsByNamesRsp extends com.qq.taf.jce.JceStruct
{
    public java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag> tags = null;

    public stGetTagDetailsByNamesRsp()
    {
    }

    public stGetTagDetailsByNamesRsp(java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag> tags)
    {
        this.tags = tags;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != tags)
        {
            _os.write(tags, 0);
        }
    }

    static java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag> cache_tags;
    static {
        cache_tags = new java.util.HashMap<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag>();
        String __var_9 = "";
        NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag __var_10 = new NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag();
        cache_tags.put(__var_9, __var_10);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.tags = (java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeedTag>) _is.read(cache_tags, 0, false);
    }

}

