// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetMaterialFeedListReq extends com.qq.taf.jce.JceStruct
{
    public String attach_info = "";

    public String feedlist_id = "";

    public stGetMaterialFeedListReq()
    {
    }

    public stGetMaterialFeedListReq(String attach_info, String feedlist_id)
    {
        this.attach_info = attach_info;
        this.feedlist_id = feedlist_id;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != attach_info)
        {
            _os.write(attach_info, 0);
        }
        if (null != feedlist_id)
        {
            _os.write(feedlist_id, 1);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attach_info =  _is.readString(0, false);
        this.feedlist_id =  _is.readString(1, false);
    }

}

