// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetMaterialFeedInfoByIdsRsp extends com.qq.taf.jce.JceStruct
{
    public java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeed> feedinfo = null;

    public stGetMaterialFeedInfoByIdsRsp()
    {
    }

    public stGetMaterialFeedInfoByIdsRsp(java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeed> feedinfo)
    {
        this.feedinfo = feedinfo;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != feedinfo)
        {
            _os.write(feedinfo, 0);
        }
    }

    static java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeed> cache_feedinfo;
    static {
        cache_feedinfo = new java.util.HashMap<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeed>();
        String __var_6 = "";
        NS_PITU_META_PROTOCOL.stMetaMaterialFeed __var_7 = new NS_PITU_META_PROTOCOL.stMetaMaterialFeed();
        cache_feedinfo.put(__var_6, __var_7);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.feedinfo = (java.util.Map<String, NS_PITU_META_PROTOCOL.stMetaMaterialFeed>) _is.read(cache_feedinfo, 0, false);
    }

}

