// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetUserSettingDataRsp extends com.qq.taf.jce.JceStruct
{
    public String attach_info = "";

    public String mengou_data = "";

    public stGetUserSettingDataRsp()
    {
    }

    public stGetUserSettingDataRsp(String attach_info, String mengou_data)
    {
        this.attach_info = attach_info;
        this.mengou_data = mengou_data;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != attach_info)
        {
            _os.write(attach_info, 0);
        }
        if (null != mengou_data)
        {
            _os.write(mengou_data, 1);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attach_info =  _is.readString(0, false);
        this.mengou_data =  _is.readString(1, false);
    }

}

