// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetTagDetailsByNamesReq extends com.qq.taf.jce.JceStruct
{
    public java.util.ArrayList<String> tag_names = null;

    public stGetTagDetailsByNamesReq()
    {
    }

    public stGetTagDetailsByNamesReq(java.util.ArrayList<String> tag_names)
    {
        this.tag_names = tag_names;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != tag_names)
        {
            _os.write(tag_names, 0);
        }
    }

    static java.util.ArrayList<String> cache_tag_names;
    static {
        cache_tag_names = new java.util.ArrayList<String>();
        String __var_8 = "";
        ((java.util.ArrayList<String>)cache_tag_names).add(__var_8);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.tag_names = (java.util.ArrayList<String>) _is.read(cache_tag_names, 0, false);
    }

}

