// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stGetMaterialFeedListAttrReq extends com.qq.taf.jce.JceStruct
{
    public String feedlist_id = "";

    public stGetMaterialFeedListAttrReq()
    {
    }

    public stGetMaterialFeedListAttrReq(String feedlist_id)
    {
        this.feedlist_id = feedlist_id;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != feedlist_id)
        {
            _os.write(feedlist_id, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.feedlist_id =  _is.readString(0, false);
    }

}

