// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stInheritBoughtMaterialReq extends com.qq.taf.jce.JceStruct
{
    public String deviceBindUid = "";

    public stInheritBoughtMaterialReq()
    {
    }

    public stInheritBoughtMaterialReq(String deviceBindUid)
    {
        this.deviceBindUid = deviceBindUid;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != deviceBindUid)
        {
            _os.write(deviceBindUid, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.deviceBindUid =  _is.readString(0, false);
    }

}

