// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stReportMaterialFeedOpReq extends com.qq.taf.jce.JceStruct
{
    public String key_name = "";

    public int type = 0;

    public int incrby = 1;

    public java.util.Map<String, String> cookie = null;

    public stReportMaterialFeedOpReq()
    {
    }

    public stReportMaterialFeedOpReq(String key_name, int type, int incrby, java.util.Map<String, String> cookie)
    {
        this.key_name = key_name;
        this.type = type;
        this.incrby = incrby;
        this.cookie = cookie;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != key_name)
        {
            _os.write(key_name, 0);
        }
        _os.write(type, 1);
        _os.write(incrby, 2);
        if (null != cookie)
        {
            _os.write(cookie, 3);
        }
    }

    static int cache_type;
    static {
        cache_type = 0;
    }
    static java.util.Map<String, String> cache_cookie;
    static {
        cache_cookie = new java.util.HashMap<String, String>();
        String __var_2 = "";
        String __var_3 = "";
        cache_cookie.put(__var_2, __var_3);
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.key_name =  _is.readString(0, false);
        this.type = (int) _is.read(type, 1, false);
        this.incrby = (int) _is.read(incrby, 2, false);
        this.cookie = (java.util.Map<String, String>) _is.read(cache_cookie, 3, false);
    }

}

