// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stSetUserSettingDataReq extends com.qq.taf.jce.JceStruct
{
    public String mengou_data = "";

    public stSetUserSettingDataReq()
    {
    }

    public stSetUserSettingDataReq(String mengou_data)
    {
        this.mengou_data = mengou_data;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != mengou_data)
        {
            _os.write(mengou_data, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.mengou_data =  _is.readString(0, false);
    }

}

