// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stSetMyMaterialFeedReq extends com.qq.taf.jce.JceStruct
{
    public boolean status = true;

    public String feed_id = "";

    public stSetMyMaterialFeedReq()
    {
    }

    public stSetMyMaterialFeedReq(boolean status, String feed_id)
    {
        this.status = status;
        this.feed_id = feed_id;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(status, 0);
        if (null != feed_id)
        {
            _os.write(feed_id, 1);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.status = (boolean) _is.read(status, 0, false);
        this.feed_id =  _is.readString(1, false);
    }

}

