// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/opalli/app_pitu_wns_interface_with_login.jce'
// **********************************************************************

package NS_PITU_CLIENT_INTERFACE_WITH_LOGIN;

public final class stSetUserSettingDataRsp extends com.qq.taf.jce.JceStruct
{
    public String attach_info = "";

    public stSetUserSettingDataRsp()
    {
    }

    public stSetUserSettingDataRsp(String attach_info)
    {
        this.attach_info = attach_info;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != attach_info)
        {
            _os.write(attach_info, 0);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.attach_info =  _is.readString(0, false);
    }

}

