// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/geraldzhu/CommClientInterface.jce'
// **********************************************************************

package CommonClientInterface;

public final class E_PLATFORM_ID implements java.io.Serializable
{
    private static E_PLATFORM_ID[] __values = new E_PLATFORM_ID[5];
    private int __value;
    private String __T = new String();

    public static final int _PLAT_ANDROID = 1;
    public static final E_PLATFORM_ID PLAT_ANDROID = new E_PLATFORM_ID(0,_PLAT_ANDROID,"PLAT_ANDROID");
    public static final int _PLAT_IPHONE = 2;
    public static final E_PLATFORM_ID PLAT_IPHONE = new E_PLATFORM_ID(1,_PLAT_IPHONE,"PLAT_IPHONE");
    public static final int _PLAT_SYB = 3;
    public static final E_PLATFORM_ID PLAT_SYB = new E_PLATFORM_ID(2,_PLAT_SYB,"PLAT_SYB");
    public static final int _PLAT_WINDOWSPHONE = 4;
    public static final E_PLATFORM_ID PLAT_WINDOWSPHONE = new E_PLATFORM_ID(3,_PLAT_WINDOWSPHONE,"PLAT_WINDOWSPHONE");
    public static final int _PLAT_OTHER = 10;
    public static final E_PLATFORM_ID PLAT_OTHER = new E_PLATFORM_ID(4,_PLAT_OTHER,"PLAT_OTHER");

    public static E_PLATFORM_ID convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static E_PLATFORM_ID convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private E_PLATFORM_ID(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
