// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/data/jcetool/taf//upload/geraldzhu/CommClientInterface.jce'
// **********************************************************************

package CommonClientInterface;

public final class stReqHeader extends com.qq.taf.jce.JceStruct
{
    public CommonClientInterface.stReqComm reqComm = null;

    public String sApply = "";

    public String sCmd = "";

    public stReqHeader()
    {
    }

    public stReqHeader(CommonClientInterface.stReqComm reqComm, String sApply, String sCmd)
    {
        this.reqComm = reqComm;
        this.sApply = sApply;
        this.sCmd = sCmd;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(reqComm, 0);
        _os.write(sApply, 1);
        _os.write(sCmd, 2);
    }

    static CommonClientInterface.stReqComm cache_reqComm;
    static {
        cache_reqComm = new CommonClientInterface.stReqComm();
    }

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.reqComm = (CommonClientInterface.stReqComm) _is.read(cache_reqComm, 0, true);
        this.sApply =  _is.readString(1, true);
        this.sCmd =  _is.readString(2, true);
    }

}

